[tool.poetry]
name = "selfie_stabilizer"
version = "0.1.0"
description = "Converts a folder of selfie images into a stabilized video."
authors = ["Jaime <jaimeliew1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.2"
dlib = "^19.23.0"
scipy = "^1.8.0"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
